# Generated by Django 5.2.4 on 2025-07-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Learn About Us', max_length=200)),
                ('title', models.CharField(default='25 Years Experience', max_length=200)),
                ('paragraphs', models.TextField(help_text='Write paragraphs separated by new lines')),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
