# Generated by Django 5.2.4 on 2025-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_serviceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('service_type', models.CharField(choices=[('haircut', 'Hair Cut'), ('hairwash', 'Hair Wash'), ('hairstraightening', 'Hair Straightening'), ('facial', 'Facial'), ('weddinghaircut', 'Wedding Haircut'), ('massage', 'Massage'), ('hairstyling', 'Hair Styling'), ('scalptreatment', 'Scalp Treatment')], max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
